name: simplist_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  animated_reorderable_list: ^1.0.8
  animations: ^2.0.11
  auto_route: ^9.1.0
  clock: ^1.1.1
  collection: ^1.18.0
  flex_seed_scheme: ^3.1.2
  fluid_animations: ^1.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3
  flutter_localizations:
    sdk: flutter
  formz: ^0.7.0
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^3.0.0
  implicitly_animated_reorderable_list_2: ^0.6.0
  intl: any # pinned by flutter sdk
  pocketbase: ^0.18.1
  pocketbased: ^0.1.0
  riverpod: ^3.0.0
  rivership: ^0.4.0
  rxdart: ^0.28.0
  sliver_tools: ^0.2.12

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lintervention: ^0.1.1
  rivership_test: ^0.2.0

flutter:
  uses-material-design: true
