name: pocketbased
description: Simple tools for pocketbase
version: 0.1.0


environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  pocketbase: ">=0.18.1 < 0.19.0"
  rxdart: ^0.28.0
  sembast: ^3.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.1.1
  
  mocktail: ^1.0.3
